### ISSUE TITLE
Mithrix Softlock

### ISSUE THREAD

**Issue by breadguyyy** [Chris-Stevenson-Git/FasterBossWait#1]
when defeating third phase of mithrix, the fourth phase doesn't spawn. getting nres from this mod so I assume its related
[LogOutput.log](https://github.com/Chris-Stevenson-Git/FasterBossWait/files/6225435/LogOutput.log)

**Comment by Chris-Stevenson-Git** [comment]
Just put a patch for this, thanks!!
